name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *" # 12시간마다 실행
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Pull GitHub User Contributions
        uses: Platane/snk@v3
        with:
          github_user_name: Doidoria
          outputs: |
            dist/github-contribution-grid-snake.svg
            dist/github-contribution-grid-snake-dark.svg

      - name: Push to output branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: output
          publish_dir: ./dist
